"use client";
import {useState} from "react";
import {Award,BarChart3,Bell,BookMarked,BookOpen,Check,ChevronRight,Clock,Flame,GraduationCap,Home,Library,Lock,Menu,Play,Radio,Search,Shield,Star,Trophy,Users,X} from "lucide-react";

const courses=[
 {title:'Segurança Patrimonial',cat:'Fundamentos',lessons:12,done:8,color:'teal',icon:Shield},
 {title:'Controle de Acesso',cat:'Procedimentos',lessons:10,done:4,color:'blue',icon:Users},
 {title:'Procedimentos de Emergência',cat:'Prevenção e resposta',lessons:14,done:2,color:'orange',icon:Flame},
 {title:'Comunicação Operacional',cat:'Rotinas profissionais',lessons:8,done:0,color:'purple',icon:BookOpen},
 {title:'Gestão de Conflitos',cat:'Comportamento',lessons:9,done:0,color:'pink',icon:Star},
 {title:'Relatório de Ocorrência',cat:'Documentação',lessons:7,done:0,color:'green',icon:BookMarked},
];
const nav=[['Início',Home],['Meus cursos',GraduationCap],['Simulados',Check],['Códigos de Comunicação',Radio],['Manual do Vigilante',Library],['Meu desempenho',BarChart3],['Certificados',Award]] as const;
const qCodes=[
 ['QAP','Está na escuta?'],['QSL','Entendido, mensagem recebida.'],['QTH','Qual é o local ou endereço?'],['QAR','Desligar.'],['QRN','Está sofrendo interferência?'],['QRA','Qual é o nome do operador ou estação?'],['QRL','Você está ocupado?'],['QRM','Há interferência humana?'],['QRQ','Transmita mais depressa.'],['QRS','Transmita mais devagar.'],['QRT','Parar transmissão.'],['QRU','Tem algo para mim?'],['QRV','Está pronto?'],['QRX','Quando vai me chamar de novo?'],['QRZ','Quem está me chamando?'],['QSA','Qual é a força do sinal?'],['QSM','Devo repetir a mensagem?'],['QSO','Comunicado ou aviso.'],['QSP','Fazer ponte para outra comunicação.'],['QTC','Há mensagens para enviar?'],['QTR','Qual é o horário exato?'],['QTU','Qual horário de operação?'],['QTA','Cancelar a última mensagem.']
];
const phonetic=[['A','Alfa'],['B','Bravo'],['C','Charlie'],['D','Delta'],['E','Echo'],['F','Fox'],['G','Golf'],['H','Hotel'],['I','Índia'],['J','Juliet'],['K','Kilo'],['L','Lima'],['M','Mike'],['N','November'],['O','Oscar'],['P','Papa'],['Q','Quebec'],['R','Romeu'],['S','Sierra'],['T','Tango'],['U','Uniform'],['V','Victor'],['W','Whiskey'],['X','X-Ray'],['Y','Yankee'],['Z','Zulu']];
const questions=[
 {q:'Qual é a principal finalidade da segurança patrimonial?',a:['Substituir os órgãos públicos','Prevenir riscos e proteger pessoas e patrimônio','Realizar investigações criminais','Aplicar penalidades'],correct:1},
 {q:'Ao identificar uma situação de emergência, o profissional deve:',a:['Agir além de sua função','Ignorar até receber ordem','Seguir o protocolo e comunicar os responsáveis','Divulgar imagens nas redes sociais'],correct:2},
 {q:'No controle de acesso, qual atitude é correta?',a:['Liberar conhecidos sem registro','Conferir autorização e registrar a entrada','Guardar documentos pessoais do visitante','Compartilhar dados com terceiros'],correct:1},
];

export default function Page(){const[active,setActive]=useState('Início');const[menu,setMenu]=useState(false);const[quiz,setQuiz]=useState(false);const go=(x:string)=>{setActive(x);setMenu(false)};return <main className="app">
<aside className={menu?'sidebar open':'sidebar'}><button className="close" onClick={()=>setMenu(false)}><X/></button><div className="brand"><img src="/trial4-guard-logo.png?v=3" alt="Logo TRIAL 4 GUARDA com escudo, número quatro e chapéu"/><div><small>TRIAL 4</small><b>GUARD</b><span>ACADEMY</span></div></div><nav><label>ESTUDOS</label>{nav.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>go(n)}><I/><span>{n}</span>{n==='Simulados'&&<em>NOVO</em>}</button>)}</nav><div className="level"><div><Trophy/><span>Nível 4</span><b>Guardião</b></div><div className="xp"><i/></div><small>1.280 / 1.500 XP</small></div><div className="profile"><i>ES</i><div><b>Evelyn Santos</b><small>Aluna</small></div></div></aside>
{menu&&<button className="scrim" onClick={()=>setMenu(false)}/>}<section className="workspace"><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><strong className="mobile-logo">TRIAL 4 <b>ACADEMY</b></strong><label className="search"><Search/><input placeholder="Buscar curso, aula ou assunto..."/><kbd>⌘ K</kbd></label><div className="head-right"><span className="streak"><Flame/> 7 dias</span><button className="bell"><Bell/></button><i className="avatar">ES</i></div></header>
{active==='Início'?<HomePage go={go} quiz={()=>setQuiz(true)}/>:<Section title={active} quiz={()=>setQuiz(true)} go={go}/>}</section>{quiz&&<Quiz close={()=>setQuiz(false)}/>}</main>}

function HomePage({go,quiz}:{go:(x:string)=>void;quiz:()=>void}){return <div className="content"><section className="hero"><div><small>CONTINUE SUA EVOLUÇÃO</small><h1>Olá, Evelyn! Pronta para estudar?</h1><p>Você concluiu <b>42%</b> da sua trilha de formação em Segurança Patrimonial.</p><button onClick={()=>go('Meus cursos')}><Play/> Continuar estudando</button></div><div className="hero-art"><div className="rings"><i/><i/><i/></div><img src="/trial4-guard-logo.png?v=3" alt="TRIAL 4 GUARDA"/><span className="badge b1"><Check/>8 aulas</span><span className="badge b2"><Flame/>7 dias</span></div></section>
<div className="stats"><article><i className="teal"><BookOpen/></i><div><span>Cursos em andamento</span><b>03</b><small>de 10 cursos</small></div></article><article><i className="orange"><Clock/></i><div><span>Tempo de estudo</span><b>18h 40min</b><small>+2h nesta semana</small></div></article><article><i className="purple"><Trophy/></i><div><span>Média nos simulados</span><b>84%</b><small>Excelente resultado</small></div></article><article><i className="green"><Award/></i><div><span>Certificados</span><b>02</b><small>8 disponíveis</small></div></article></div>
<div className="heading"><div><h2>Continue estudando</h2><p>Retome de onde você parou</p></div><button onClick={()=>go('Meus cursos')}>Ver todos <ChevronRight/></button></div><section className="continue"><div className="lesson-cover"><span>SEGURANÇA PATRIMONIAL</span><Shield/><i>08</i></div><div className="lesson-info"><small>MÓDULO 2 • AULA 8 DE 12</small><h2>Os 4 pilares da segurança</h2><p>Prevenção, Vigilância, Resposta e Gestão aplicadas à rotina profissional.</p><div className="course-progress"><div><span>Progresso do curso</span><b>67%</b></div><div><i/></div></div><button><Play/> Continuar aula</button></div><aside><b>Próximas aulas</b>{['Ronda e pontos vulneráveis','Comunicação de ocorrências','Avaliação do módulo'].map((x,i)=><div key={x}><i>{i+9}</i><span>{x}<small>{i===2?'Prova • 10 questões':(8+i*3)+' min'}</small></span>{i===2?<Lock/>:<Play/>}</div>)}</aside></section>
<div className="two-cols"><section><div className="heading"><div><h2>Trilhas de aprendizagem</h2><p>Conteúdos essenciais para sua formação</p></div><button onClick={()=>go('Meus cursos')}>Explorar cursos <ChevronRight/></button></div><div className="course-grid">{courses.slice(0,4).map(c=><button className="course" key={c.title} onClick={()=>go('Meus cursos')}><i className={c.color}><c.icon/></i><small>{c.cat}</small><b>{c.title}</b><span>{c.lessons} aulas • {c.done?c.done+' concluídas':'Não iniciado'}</span><div><i style={{width:`${c.done/c.lessons*100}%`}}/></div></button>)}</div></section><aside className="challenge"><small>DESAFIO DA SEMANA</small><div className="trophy"><Trophy/></div><h2>Simulado de Segurança</h2><p>Teste seus conhecimentos com 20 questões e receba o resultado na hora.</p><div className="challenge-stats"><span><b>20</b> questões</span><span><b>30</b> minutos</span><span><b>70%</b> aprovação</span></div><button onClick={quiz}>Iniciar simulado</button></aside></div>
<section className="manual"><i><Library/></i><div><small>BIBLIOTECA DE CONHECIMENTO</small><h2>Manual do Vigilante Patrimonial</h2><p>Leis essenciais, história da profissão, procedimentos e exemplos práticos em um só lugar.</p></div><button onClick={()=>go('Manual do Vigilante')}>Acessar o manual <ChevronRight/></button></section></div>}

function Section({title,quiz,go}:{title:string;quiz:()=>void;go:(x:string)=>void}){if(title==='Códigos de Comunicação')return <CodesSection go={go}/>;const isCourses=title==='Meus cursos';return <div className="content section-page"><button className="back" onClick={()=>go('Início')}>← Voltar ao início</button><div className="section-hero"><small>TRIAL 4 ACADEMY</small><h1>{title}</h1><p>{title==='Simulados'?'Pratique com questões comentadas e acompanhe sua evolução.':title==='Manual do Vigilante'?'Consulte conteúdos essenciais, leis e aplicações práticas.':'Continue avançando na sua formação profissional.'}</p>{title==='Simulados'&&<button onClick={quiz}>Iniciar simulado de 20 questões</button>}</div>{isCourses&&<div className="all-courses">{courses.map(c=><article key={c.title}><i className={c.color}><c.icon/></i><div><small>{c.cat}</small><h3>{c.title}</h3><p>{c.lessons} aulas • {c.done?c.done+' concluídas':'Não iniciado'}</p><div><i style={{width:`${c.done/c.lessons*100}%`}}/></div></div><button>{c.done?'Continuar':'Começar'} <ChevronRight/></button></article>)}</div>}{!isCourses&&title!=='Simulados'&&<div className="placeholder"><BookOpen/><h2>Conteúdo em preparação</h2><p>Esta área já está organizada para receber o conteúdo completo do aplicativo.</p></div>}</div>}

function CodesSection({go}:{go:(x:string)=>void}){return <div className="content section-page codes-page"><button className="back" onClick={()=>go('Início')}>← Voltar ao início</button><div className="section-hero codes-hero"><small>COMUNICAÇÃO OPERACIONAL</small><h1>Códigos de Comunicação</h1><p>Consulte rapidamente os Códigos Q e o Alfabeto Fonético Internacional.</p></div><div className="codes-layout"><section className="code-panel"><header><i><Radio/></i><div><small>RÁDIO COMUNICAÇÃO</small><h2>Códigos Q</h2></div><span>{qCodes.length} códigos</span></header><div className="q-code-grid">{qCodes.map(([code,meaning])=><article key={code}><b>{code}</b><p>{meaning}</p></article>)}</div></section><section className="code-panel"><header><i><BookOpen/></i><div><small>IDENTIFICAÇÃO CLARA</small><h2>Alfabeto Fonético</h2></div><span>26 letras</span></header><div className="phonetic-grid">{phonetic.map(([letter,word])=><article key={letter}><b>{letter}</b><span>{word}</span></article>)}</div></section></div></div>}

function Quiz({close}:{close:()=>void}){const[index,setIndex]=useState(0);const[selected,setSelected]=useState<number|null>(null);const[score,setScore]=useState(0);const[done,setDone]=useState(false);const q=questions[index];const next=()=>{if(selected===q.correct)setScore(score+1);if(index===questions.length-1)setDone(true);else{setIndex(index+1);setSelected(null)}};return <div className="modal-wrap"><button className="modal-bg" onClick={close}/><section className="quiz-modal"><header><div><small>SIMULADO RÁPIDO</small><b>{done?'Resultado':`Questão ${index+1} de ${questions.length}`}</b></div><button onClick={close}><X/></button></header>{done?<div className="result"><i><Trophy/></i><h2>Simulado concluído!</h2><p>Você acertou <b>{score} de {questions.length}</b> questões.</p><button onClick={close}>Voltar aos estudos</button></div>:<><div className="quiz-bar"><i style={{width:`${(index+1)/questions.length*100}%`}}/></div><h2>{q.q}</h2><div className="answers">{q.a.map((a,i)=><button key={a} className={selected===i?'selected':''} onClick={()=>setSelected(i)}><i>{String.fromCharCode(65+i)}</i>{a}</button>)}</div><footer><span>Selecione uma alternativa</span><button disabled={selected===null} onClick={next}>{index===questions.length-1?'Finalizar':'Próxima questão'} <ChevronRight/></button></footer></>}</section></div>}
